#### 특성(Feature) 공학과 규제(Regularization: 정형화, 일반화 규제)

In [58]:
import pandas as pd

In [59]:
df = pd.read_csv("../Data/fish.csv")
df.head()

,length,height,width
0,8.4,2.11,1.41
1,13.7,3.53,2.00
2,15.0,3.82,2.43
3,16.2,4.59,2.63
4,17.4,4.59,2.94


In [60]:
fish_full = df.to_numpy()
fish_full[:5]


array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94]])

In [61]:
df = pd.read_csv("../Data/fish_weight.csv")
df.head()

,weight
0,5.9
1,32.0
2,40.0
3,51.5
4,70.0


In [62]:
fish_weight = df.to_numpy()
fish_weight[:5]

array([[ 5.9],
       [32. ],
       [40. ],
       [51.5],
       [70. ]])

In [63]:
# Train과 Test
from sklearn.model_selection import train_test_split

In [64]:
train_input, test_input, train_target, test_target = \
    train_test_split(
        fish_full,
        fish_weight,
        random_state=42
    )


#### sklearn 으로 다중회귀 분석하기

----
#### 다항 특성 만들기 연습

In [65]:
from sklearn.preprocessing import PolynomialFeatures

In [66]:
# 다항 특성 만들기
poly = PolynomialFeatures(include_bias=False) # degree = 2
poly.fit_transform([[2,3]])

array([[2., 3., 4., 6., 9.]])

In [67]:
poly.get_feature_names_out()

array(['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2'], dtype=object)

----

#### 다항 특성 만들기

In [68]:
train_input.shape

(42, 3)

In [69]:
# train_input을 다항 특성 만들기
poly = PolynomialFeatures(include_bias=False) # degree = 2
train_poly = poly.fit_transform(train_input)


In [70]:
train_poly.shape

(42, 9)

In [71]:
# 컬럼 정보 확인
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2'], dtype=object)

In [72]:
train_poly[:5]

array([[  19.6   ,    5.14  ,    3.04  ,  384.16  ,  100.744 ,   59.584 ,
          26.4196,   15.6256,    9.2416],
       [  22.    ,    5.88  ,    3.52  ,  484.    ,  129.36  ,   77.44  ,
          34.5744,   20.6976,   12.3904],
       [  18.7   ,    5.2   ,    3.12  ,  349.69  ,   97.24  ,   58.344 ,
          27.04  ,   16.224 ,    9.7344],
       [  17.4   ,    4.59  ,    2.94  ,  302.76  ,   79.866 ,   51.156 ,
          21.0681,   13.4946,    8.6436],
       [  36.    ,   10.61  ,    6.74  , 1296.    ,  381.96  ,  242.64  ,
         112.5721,   71.5114,   45.4276]])

In [73]:
# test_input도 다항특성 만들기
test_poly = poly.transform(test_input)
test_poly.shape

(14, 9)

#### 다중 회귀 모델 훈련하기

In [74]:
from sklearn.linear_model import LinearRegression

In [75]:
import numpy as np

In [76]:
lr = LinearRegression()
lr.fit(train_input, train_target)
print("Train:", lr.score(train_input, train_target))
print("Test:", lr.score(test_input, test_target))

Train: 0.9559326821885706
Test: 0.8796419177546367


In [77]:
lr = LinearRegression()
lr.fit(train_poly, train_target)
print("Train:", lr.score(train_poly, train_target))
print("Test:", lr.score(test_poly, test_target))

Train: 0.9903183436982126
Test: 0.9714559911594095


----
#### 더 많은 특성 만들기

In [88]:
poly = PolynomialFeatures(include_bias=False, degree=5)
poly.fit(train_input)
train_poly = poly.transform(train_input)
test_poly = poly.transform(test_input)


In [89]:
train_poly.shape

(42, 55)

In [90]:
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2', 'x0^3', 'x0^2 x1', 'x0^2 x2', 'x0 x1^2', 'x0 x1 x2',
       'x0 x2^2', 'x1^3', 'x1^2 x2', 'x1 x2^2', 'x2^3', 'x0^4', 'x0^3 x1',
       'x0^3 x2', 'x0^2 x1^2', 'x0^2 x1 x2', 'x0^2 x2^2', 'x0 x1^3',
       'x0 x1^2 x2', 'x0 x1 x2^2', 'x0 x2^3', 'x1^4', 'x1^3 x2',
       'x1^2 x2^2', 'x1 x2^3', 'x2^4', 'x0^5', 'x0^4 x1', 'x0^4 x2',
       'x0^3 x1^2', 'x0^3 x1 x2', 'x0^3 x2^2', 'x0^2 x1^3',
       'x0^2 x1^2 x2', 'x0^2 x1 x2^2', 'x0^2 x2^3', 'x0 x1^4',
       'x0 x1^3 x2', 'x0 x1^2 x2^2', 'x0 x1 x2^3', 'x0 x2^4', 'x1^5',
       'x1^4 x2', 'x1^3 x2^2', 'x1^2 x2^3', 'x1 x2^4', 'x2^5'],
      dtype=object)

In [93]:
lr.fit(train_poly, train_target)
print("Train : ", lr.score(train_poly, train_target))
print("Test  : ", lr.score(test_poly, test_target))

Train :  0.9999999999976599
Test  :  -144.4072001577299


#### 규제
모델이 과적합되게 학습하지 않고 일반성을 가질 수 있도록 규제(정규화) 하는 것

In [94]:
# 규제 전에 표준화
from sklearn.preprocessing import StandardScaler

In [95]:
ss = StandardScaler()
ss.fit(train_poly)

train_scaled = ss.transform(train_poly)
test_scaled = ss.transform(test_poly)

#### Rideg(L2규제) 규제
: 가중치의 제곱으로 규제하는 방법이다. 

In [96]:
from sklearn.linear_model import Ridge

In [98]:
ridge = Ridge() # default : alpha = 1
ridge.fit(train_scaled, train_target)
print("Train : ", ridge.score(train_scaled, train_target))
print("Test : ", ridge.score(test_scaled, test_target))

Train :  0.9896101671037343
Test :  0.9790693977615391


#### 적절한 규제 강도(Hyper parameter) 찾기

In [99]:
train_score = []
test_score = []
alpha_list = [0.001, 0.01, 0.1, 1, 10, 100] # 임의로 정한다.

for alpha in alpha_list:
    ridge = Ridge(alpha=alpha)
    ridge.fit(train_scaled, train_target)
    train_score.append(ridge.score(train_scaled, train_target))
    test_score.append(ridge.score(test_scaled, test_target))

In [103]:
pd.DataFrame(
    {
        'Train' : train_score,
        'Test' : test_score
    }
)

,Train,Test
0,0.993046,0.956939
1,0.991781,0.980019
2,0.990382,0.982798
3,0.989610,0.979069
4,0.988728,0.972533
5,0.984184,0.962704


In [102]:
ridge = Ridge(alpha=0.1) # default : alpha = 1
ridge.fit(train_scaled, train_target)
print("Train : ", ridge.score(train_scaled, train_target))
print("Test : ", ridge.score(test_scaled, test_target))

Train :  0.9903815817570368
Test :  0.9827976465386892
