# 1. ndArray

### (1) ndArray 생성

- 형식 : numpy.array()함수에 객체를 인자로 추가하여 생성한다.
- 객체로 파이썬의 리스트를 생성하여 입력하여 자동으로 변환된다.

In [10]:
import numpy as np

# 1차원 배열 생성
list1 = [1, 2, 3]
array1 = np.array(list1)
print(type(list1), type(array1))

array2 = np.array([1, 2, 3])
print(type(array2))


<class 'list'> <class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
# 튜플을 ndarray로 변환하여 생성
tuple1 = (1, 2, 3)
tarray1 = np.array(tuple1)
print(type(tarray1))
print(tarray1)

<class 'numpy.ndarray'>
[1 2 3]


In [9]:
# 세트를 ndarray로 변환하여 생성
set1 = {1, 2, 3}
sarray1 = np.array(set1)
print(type(sarray1))
print(sarray1)

<class 'numpy.ndarray'>
{1, 2, 3}


In [7]:
print(array1)
print(tarray1)
print(sarray1)

[1 2 3]
[1 2 3]
{1, 2, 3}


In [11]:
# 2차원 배열 생성
array2 = np.array([[1, 2], [3, 4]]) # 중첩 리스트 사용
print(type(array2))
print(array2)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [12]:
# 3차원 배열 생성
list3 = [[[1, 2], [3, 4]]]
array3 = np.array(list3)
print(type(array3))
print(array3)

<class 'numpy.ndarray'>
[[[1 2]
  [3 4]]]


### (2) shape와 ndim
- shape : 배열의 모양(형태)
- ndim : 배열의 차원

In [14]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1], [2], [3]])
array3 = np.array([[[1]], [[2]], [[3]]])

In [16]:
print(f"1차원: {array1.shape}")
print(f"2차원: {array2.shape}")
print(f"3차원: {array3.shape}")

1차원: (3,)
2차원: (3, 1)
3차원: (3, 1, 1)


In [18]:
print(f"1차원 : {array1.ndim}")
print(f"2차원 : {array2.ndim}")
print(f"3차원 : {array3.ndim}")

1차원 : 1
2차원 : 2
3차원 : 3


### (3) dtype 
- 저장된 데이터 타입 확인
- 모든 데이터 타입이 동일 해야함

In [22]:
# 정수 배열
arr_int = np.array([1, 2, 3])
print(type(arr_int))
print(arr_int.dtype)

<class 'numpy.ndarray'>
int64


In [24]:
# 실수 배열
arr_float = np.array([1.23, 2.34, 3.0])
print(type(arr_float))
print(arr_float.dtype)

<class 'numpy.ndarray'>
float64


In [25]:
# 문자열 배열
arr_str = np.array(['a', 'b', 'c'])
print(type(arr_str))
print(arr_str.dtype)

<class 'numpy.ndarray'>
<U1


## (4) 자동 형변환
- 여러타입이 저장되는 경우 가장 큰 타입으로 자동 변환

In [27]:
# 정수 + 문자열 => 문자열 타입 저장
arr = np.array([1, 2, 'abc'])
arr

array(['1', '2', 'abc'], dtype='<U21')

In [28]:
# 정수 + 실수 => 실수 타입으로 저장
arr = np.array([1, 2, 3.123])
arr

array([1.   , 2.   , 3.123])

In [31]:
# 실수 + 문자열 => 문자열 타입 저장 : 정수 < 실수 < 문자열
arr = np.array([1.0, 2.12, 'test'])
arr

array(['1.0', '2.12', 'test'], dtype='<U32')

# (5) 데이터 타입 변환 -astype()
- 데이터 타입을 명시적으로 변환
- 자주 사용하는 dtype 종류
  |dtype|설명|메모리|
  |--------|----|------|
  |int32|32비트 정수|4바이트|
  |int64|64비트 정수(기본값)|8바이트|
  |float32|32비트 실수|4바이트|
  |float64|64비트 실수(기본값)|8바이트|
  |bool|불린(True/False)|1바이트|
  |<U숫자|유니코드 문자열|가변|

In [36]:
arr_int32 = np.array([1, 2, 3])
arr_int32.dtype

dtype('int64')

In [37]:
# arr_int 배열을 float64 타입의 배열로 변환
arr_float = arr_int32.astype('float64')
arr_float

array([1., 2., 3.])

In [38]:
# arr_int32 배열을 문자열 배열로 변환
arr_str = arr_int32.astype('<U1')
arr_str

array(['1', '2', '3'], dtype='<U1')

### (6) 데이터 생성 함수 - arange()
- 파이썬의 range() 함수와 유사하며, 연속된 데이터를 생성
- np.arange(start, end, step)

In [39]:
# 0~9 까지 데이터 생성
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# 0~1까지 0.2만큼씩 증가
arr = np.arange(0, 2, 0.2)
arr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

### (7) np.zeros(), np.ones()
- np.zeros() : 모든 데이터가 0인 배열
- np.ones() : 모든 데이터가 1인 배열

In [45]:
# 3행의 1차원 배열 생성 후, 모든 데이터를 0으로 초기화
arr_zeros = np.zeros((3, ), dtype='int64')
arr_zeros

array([0, 0, 0])

In [46]:
# 모든 데이터를 0으로 갖는 3행 4열의 2차원 배열 생성
arr_zeros = np.zeros((3, 4), dtype='int64')
arr_zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
# 모든 원소를 정수 1로 가지는 5행의 1차원 배열 생성
arr_ones = np.ones((5,), dtype='int64')
arr_ones

array([1, 1, 1, 1, 1])

In [50]:
# 모든 원소를 실수 1로 가지는 2행 5열의 2차원 배열 생성
arr_ones = np.ones((2, 5), dtype='float64')
arr_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### (8) np.linespace()
- np.linespace(start, end, number)
- 시작과 끝 사이의 값을 균등하게 나누어 배열 생성

In [51]:
arr_lin = np.linspace(1, 2,  5)
arr_lin

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

### (9) np.random()
- 0과 1사이의 난수를 발생
- rand(shape) 함수를 이용하여 실수를 배열 생성
- randint(high, size = shape)

In [54]:
# 난수를 발생하여 3행의 1차원 배열 생성
arr_random = np.random.rand(3,)
arr_random

array([0.37628983, 0.67404148, 0.20085733])

In [55]:
# 난수를 발생하여 5보다 작은 정수들만, 3행 1차원 배열 생성
arr_random = np.random.randint(5, size=(3,))
arr_random

array([1, 2, 0], dtype=int32)

In [67]:
# 난수를 발생하여 10보다 작은 정수들만, 3행 5열의 2차원 배열 생성
arr_random = np.random.randint(10, size=(3, 5))
arr_random

array([[2, 6, 0, 3, 9],
       [9, 4, 5, 6, 3],
       [3, 3, 1, 6, 3]], dtype=int32)

### (10) axis - 배열의 축
- 2차원 배열의 axis=0은 row(행), axis=1 column(컬럼) 방향을 의미

In [77]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) #2행 3열
print(arr)
arr.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [78]:
# 행(가로) 기준으로 합계 계산
arr_row_sum = np.sum(arr, axis=0)
arr_row_sum
# 1 2 3
# 4 5 6 

array([5, 7, 9])

In [79]:
# 컬럼(세로) 기준으로 합계 계산
arr_col_sum = np.sum(arr, axis=1)
arr_col_sum

array([ 6, 15])

### (11) reshape()
- 배열의 형태를 바꾸는 함수
- 배열의 원소 개수를 유지하면서 변환해야 함

In [80]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
# 1차원 arr 객체를 2행 5열의 2차원 배열로 변환
arr2 = np.reshape(arr, (2, 5))
print(arr2.shape)
print(arr2)

(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [87]:
# 2행 5열의 2차원 배열을 1차원 배열로 변환
arr3 = np.reshape(arr, (10, ))
print(arr3.shape)
print(arr3)

(10,)
[0 1 2 3 4 5 6 7 8 9]


In [88]:
arr4 = np.arange(12).reshape((3, 4))
print(arr4.shape)
print(arr4)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [89]:
arr5 = np.reshape(arr4, (2,6))
print(arr5.shape)
print(arr5)

(2, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


- -1을 사용 하여 자동 계산

In [90]:
arr = np.arange(10)

In [91]:
# 5열의 2차원 배열로 생성 - 컬럼은 고정, 행은 자동계산(-1)
arr2 = np.reshape(arr, (-1, 5))
print(arr2.shape)
print(arr)

(2, 5)
[0 1 2 3 4 5 6 7 8 9]


In [92]:
arr3 = np.reshape(arr, (2, -1))
print(arr3.shape)
print(arr3)

(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [93]:
# 원소 갯수 256개 2컬럼을 가진 2차원 배열 생성
arr4 = np.arange(256).reshape((-1, 2))
arr4.shape

(128, 2)

In [97]:
# 8개 원소를 가진 1차원 배열 => 3차원 배열로 변환
arr_3d = np.arange(8).reshape((2, 2, 2))
arr_3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [98]:
# 3차원 배열 => 1차원 변환
arr_1d = np.reshape(arr_3d, (8,))
print(arr_1d.shape)
print(arr_1d)

(8,)
[0 1 2 3 4 5 6 7]


In [104]:
# (1) [10, 20, 30, 40, 50]으로 1차원 배열을 생성하세요.
arr1 = np.arange(10, 60, 10)
arr1

array([10, 20, 30, 40, 50])

In [105]:
# (2) [[1, 2, 3], [4, 5, 6], [7, 8, 9]]으로 2차원 배열을 생성하세요.
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
# (3) 위 두 배열의 shape, dtype, ndim을 각각 출력하세요.
print(f"shape : {arr1.shape} dtype: {arr1.dtype} ndim: {arr1.ndim}")

shape : (5,) dtype: int64 ndim: 1


In [113]:
# 2. 0부터 19까지의 1차원 배열을 np.arange()로 생성하세요.
arr1_1d = np.arange(20)
arr1_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [114]:
# (1) 위 배열을 4행 5열의 2차원 배열로 변환하세요.
arr1_2d = np.reshape(arr1_1d, (4, 5))
arr1_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [115]:
# (2) 모든 원소가 0인 3행 4열 배열을 생성하세요 (dtype: int32) 
arr1_zeros = np.zeros((3, 4), dtype='int32')
arr1_zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [118]:
# (3) 0부터 1까지 6개의 균등한 숫자 배열을 생성하세요.
arr1_lin = np.linspace(0, 1, 6)
arr1_lin

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])