# 배열 연산
- 배열의 shape이 같으면 데이터별로 연산이 진행됨

In [3]:
import numpy as np

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1.shape, arr2.shape)
print(arr1, arr2)

(3,) (3,)
[1 2 3] [4 5 6]


In [ ]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

In [11]:
# shape이 다른 경우 valueError 발생
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 5, 6])
print(arr1.shape, arr2.shape)
print(arr1, arr2)

(4,) (3,)
[1 2 3 4] [4 5 6]


- 스칼라(단일 숫자)

In [14]:
print(arr1 + 10)
print(arr1 - 10)
print(arr1 * 10)
print(arr1 / 10)

[11 12 13 14]
[-9 -8 -7 -6]
[10 20 30 40]
[0.1 0.2 0.3 0.4]


- 2차원 배열 연산

In [15]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1.shape, arr2.shape)

(2, 2) (2, 2)


In [16]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


# 정렬 - sort()와 argsort()

### (1) sort()
- numpy.sort() vs numpy.ndarray.sort() : 원본 배열의 유지 여부가 핵심
- 원본 유지 O : numpy.sort()
- 원본 유지 X : numpy.ndarray.sort()
- numpy.sort() 사용을 권장함!!

In [20]:
org_arr = np.array([2, 1, 3, 6, 9])
org_arr

array([2, 1, 3, 6, 9])

In [21]:
# 오를차순 정률 후 새 배열 반환
sort_arr = np.sort(org_arr)
sort_arr

array([1, 2, 3, 6, 9])

In [22]:
print(org_arr, sort_arr)

[2 1 3 6 9] [1 2 3 6 9]


In [23]:
# 원본 배열을 직접 오름차순 정렬
org_arr.sort()
print(org_arr)

[1 2 3 6 9]


- 내림차순 정렬 : 배열[::-1]

In [26]:
org_arr = np.array([8, 4, 9, 2, 5])
sort_arr = np.sort(org_arr)[::-1]
sort_arr

array([9, 8, 5, 4, 2])

In [30]:
org_arr = np.array([8, 4, 9, 2, 5])
org_arr.sort()
org_arr[::-1]

array([9, 8, 5, 4, 2])

- 2차원 배열 정렬

In [31]:
arr = np.array([[8, 12],
                [7, 1]])
arr

array([[ 8, 12],
       [ 7,  1]])

In [32]:
sort_arr = np.sort(arr)
sort_arr

array([[ 8, 12],
       [ 1,  7]])

In [35]:
sort_arr = np.sort(arr, axis=0)
sort_arr

array([[ 7,  1],
       [ 8, 12]])

In [36]:
sort_arr2 = np.sort(sort_arr, axis=1)
sort_arr2

array([[ 1,  7],
       [ 8, 12]])

### (2) argsort()
- 정렬된 인덱스 반환

In [41]:
names = np.array(['홍길동','김유신','강감찬','이순신','스미스'])
scores = np.array([72, 81, 95, 66, 88])

In [44]:
# 성적순으로  names 배열을 오름차순 정렬
sort_idx = np.argsort(scores)  # 인덱스 반환 : [3, 0, 1, 4, 2]
sort_idx

array([3, 0, 1, 4, 2])

In [45]:
# 정렬한 인덱스를 팬시 인덱싱 실행
names[sort_idx]

array(['이순신', '홍길동', '김유신', '스미스', '강감찬'], dtype='<U3')

In [46]:
# 성적순으로  names 배열을 내림차순 정렬
sort_idx2 = np.argsort(scores)[::-1]
names[sort_idx]

array(['이순신', '홍길동', '김유신', '스미스', '강감찬'], dtype='<U3')

# 집계 함수

In [47]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
print(np.sum(arr)) # 합계
print(np.mean(arr)) # 평균
print(np.max(arr)) # 최대값
print(np.min(arr)) # 최소값
print(np.std(arr)) # 표준편차
print(np.var(arr)) # 분산
print(np.median(arr)) # 중앙값

45
5.0
9
1
2.581988897471611
6.666666666666667
5.0


In [52]:
arr = np.array([2, 3, 1, 20, 7, 8])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

41
6.833333333333333
5.0


- 2차원 배열에서 집계함수 사용

In [55]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(f"전체 합계 : {np.sum(arr)}")
print(f"행기준 합계 : {np.sum(arr, axis=0)}")
print(f"행기준 합계 : {np.sum(arr, axis=1)}")

print(f"행기준 평균 : {np.mean(arr, axis=0)}")
print(f"행기준 평균 : {np.mean(arr, axis=1)}")

전체 합계 : 21
행기준 합계 : [5 7 9]
행기준 합계 : [ 6 15]
행기준 평균 : [2.5 3.5 4.5]
행기준 평균 : [2. 5.]


# 선형 대수 연산

### (1) 행렬 내적(dot product)
- 행렬의 곱셈은 dot 함수 사용
  예) A(2,3) * B(3,2) = C(2,2)
- 규칙 : A의 열 수 === B의 행 수가 동일할 때만 내적 연산이 가능함

In [58]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
C = np.dot(A, B)
print(f"A : {A}")
print(f"B : {B}")
print(f"C : {C}")

A : [[1 2 3]
 [4 5 6]]
B : [[ 7  8]
 [ 9 10]
 [11 12]]
C : [[ 58  64]
 [139 154]]


### (2) 전치 행렬
- np.transpose() 함수를 이용하여 행과 열을 바꿈

In [63]:
A_T = np.transpose(A)
print(A.shape)
print(A_T.shape)
print(A, "\n", A_T)

(2, 3)
(3, 2)
[[1 2 3]
 [4 5 6]] 
 [[1 4]
 [2 5]
 [3 6]]


# 기타 함수

### (1) np.where()
- 조건에 따라 값을 선택함

In [65]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# 5보다 큰 값만 출력
idx = np.where(arr>5)
print(idx)
arr2 = arr[idx]
print(arr2)

(array([5, 6, 7, 8]),)
[6 7 8 9]


### (2) np.unique()
- 중복 없는 고유한 값을 반환

In [72]:
arr = np.array([1, 2, 3, 3, 2, 1, 4, 5])
print(np.unique(arr))

[1 2 3 4 5]


In [73]:
# value, count 출력
values, counts = np.unique(arr, return_counts=True)
print(values)
print(counts)

[1 2 3 4 5]
[2 2 2 1 1]


### (3) np.concatenate()
- 배열을 이어붙이기

In [75]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate([a, b])
c

array([1, 2, 3, 4, 5, 6])